### PR TITLE
Fix kafka internal docker connection

### PR DESCRIPTION
**Pull request by mdelapenya**
Hey @catinapoke, I'm sending a PR to your main branch (the one you used to send the original PR).

## What does this PR do?
This PR is merging the current state of main with the branch, adding commits for:

- return back to PLAINTEXT/BROKER, instead of EXTERNAL/INTERNAL. This is caused because there could be expectations on current users on those names. But I'd be open to a rename in a separate PR if you consider it important. We can then isolate that breaking change from the current bug fix.
- updates usage of deprecated RunContainer, with Run. Same for network creation APIs.
- resolve some lint errors, such as error handling, indentation and sarama client closing.
- refactors a test using subtests instead of different blocks in the same test. I think this improves readability.
- adds a test using kcat, shadowing what the redpanda module does. I left the test using `initKafkaTest` untouched on purpose, I hope you can work on that replacing the current logic with the kcat example. 🙏 

I think there are other tests needing the kcat

## Why is it important?
Unblock https://github.com/testcontainers/testcontainers-go/pull/2490

## Related issues

- Relates https://github.com/testcontainers/testcontainers-go/pull/2490

### CODE REVIEW

**Comment by catinapoke** [comment]
LGTM
So things is left - TestKafka_restProxyService and TestKafka_networkConnectivity (remake to kcat by example)

**Comment by mdelapenya** [comment]
@catinapoke how do you want to proceed with this? Merge into your branch and then add kcat to those tests?

**Comment by catinapoke** [comment]
Yes, going to redo test with kcat

**Comment by catinapoke** [comment]
Btw, have you run tests? I see my tests fail now at basic stuff :/

**Comment by catinapoke** [comment]
uhm, yea, I see in Github tests details 

2024/09/09 18:10:15 🐳 Starting container: c5830d4ef694
2024/09/09 18:10:20 ✅ Container started: c5830d4ef694
2024/09/09 18:10:20 🔔 Container is ready: c5830d4ef694
    kafka_test.go:142: 
        	Error Trace:	/home/runner/work/testcontainers-go/testcontainers-go/modules/kafka/kafka_test.go:142
        	Error:      	Received unexpected error:
        	            	failed to create topics: kafka: broker not connected
        	Test:       	TestKafka_networkConnectivity

=== FAIL: . TestTrimValidateListeners/#03 (re-run 5) (0.00s)
    kafka_helpers_test.go:214: expected to fail due to reserved listener name PLAINTEXT duplication
    --- FAIL: TestTrimValidateListeners/#03 (0.00s)

=== FAIL: . TestTrimValidateListeners (re-run 5) (0.00s)

=== FAIL: . TestKafka (re-run 5) (5.27s)
2024/09/09 18:10:21 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 26.1.3
  API Version: 1.45
  Operating System: Ubuntu 22.04.4 LTS
  Total Memory: 15981 MB
  Testcontainers for Go Version: v0.34.0
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 16bd96c67741897b2ff88f00d299db0b40d32d12a20ead0e88649d9c5b46481c
  Test ProcessID: 5486db9c-3b38-476f-bb8d-fd77d4e4b4c0
2024/09/09 18:10:21 🐳 Creating container for image testcontainers/ryuk:0.9.0
2024/09/09 18:10:21 ✅ Container created: 94bfd7836393
2024/09/09 18:10:21 🐳 Starting container: 94bfd7836393
2024/09/09 18:10:21 ✅ Container started: 94bfd7836393
2024/09/09 18:10:21 ⏳ Waiting for container id 94bfd7836393 image: testcontainers/ryuk:0.9.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms skipInternalCheck:false}
2024/09/09 18:10:21 🔔 Container is ready: 94bfd7836393

**Comment by catinapoke** [comment]
@mdelapenya looks like something has been broken after your changes (or before your and after mine, I dunno)

upd. fixed basic test for kafka, but network one is still broken

**Pull request merged**
